name: calendart_example
description: Example App for 'calendart' package

version: 1.0.0

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  intl: ^0.16.1
  combos: ^1.2.0
  editors: ^0.0.9
  demo_items:
    git:
      url: https://github.com/creomobile/demo_items
  combos_example:
    git:
      url: https://github.com/creomobile/combos
      path: example/
  calendart: any

dependency_overrides:
  calendart:
    path: ../

dev_dependencies:
  pedantic: ^1.8.0

flutter:
  uses-material-design: true
