name: calendart_example
description: Example App for 'calendart' package

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  combos: ^1.1.5
  editors: ^0.0.3+2
  demo_items:
    git:
      url: https://github.com/creomobile/demo_items
  calendart:
    path: ../

dev_dependencies:
  pedantic: ^1.8.0

flutter:
  uses-material-design: true
