name: calendart_example
description: Example App for 'calendart' package

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  calendart:
    path: ../
  cupertino_icons: ^0.1.3

dev_dependencies:
  pedantic: ^1.8.0

flutter:
  uses-material-design: true
