name: calendart
description: High customizable Flutter calendar widgets with popup view and multi-columns/rows of months, multi-scroll directions, multi-selections.
version: 1.0.4+3
homepage: https://github.com/creomobile/calendart

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  combos: ^1.1.7+6

dev_dependencies:
  pedantic: ^1.8.0

flutter:
