name: calendart
description: Flutter calendar widget with customizable items and selection methods.
version: 1.0.0
homepage: https://github.com/creomobile/calendart

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  combos: ^1.1.6

dev_dependencies:
  pedantic: ^1.8.0

flutter:
